### PR TITLE
PS-1798 Allow query and processed_tags for branches

### PR DESCRIPTION
**Pull request by pivnicek**
Required for https://github.com/keboola/output-mapping/pull/78

### CODE REVIEW

**Comment by pivnicek** [comment]
@odinuv gentle reminder:).  this one is blocking keboola/output-mapping#78

**Comment by odinuv** [comment]
why do you need to enable query?

**Comment by pivnicek** [comment]
@odinuv ah damn, I suppose I don't.  but I'm not sure why it's disaabled in the first place

**Comment by odinuv** [comment]
it's disabled because on dev branch the query would be the same as on the prod branch, and there is no reasonable way to rewrite it, so the dev branch would work with production files

**Review by odinuv — APPROVED** [review]

**Pull request merged**
