### PR TITLE
fix: Pass format to the strategy

### PR DESCRIPTION
**Pull request by pivnicek**
slack: https://keboola.slack.com/archives/CQB468K63/p1606995849121400

### CODE REVIEW

**Review by odinuv — COMMENTED** [review]
it's missing a test

**Comment by pivnicek** [comment]
yeah, feck, I'll add one

**Comment by pivnicek** [comment]
I put there a test and confirmed that without passing the 5th param it produced the error we saw today.

**Comment by pivnicek** [comment]
@odinuv ping, sorry, but those transformations need this :-(

**Review by odinuv — APPROVED** [review]
lgbt

**Comment by odinuv** [comment]
sorry for long wait, but at the same time, this you can't deploy it today anyway

**Pull request merged**
